import {Outfit} from 'next/font/google'
import "./globals.css";


export const metadata = {
  title: "AI-Study-Material-Generator",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        {children}
      </body>
    </html>
  );
}
